"""create users and user_addresses tables

Revision ID: 4ad2b65b1fb4
Revises: cedcfebfb6ad
Create Date: 2025-09-01 13:38:14.539433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad2b65b1fb4'
down_revision: Union[str, None] = 'cedcfebfb6ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
