"""Add Basket model

Revision ID: b022a93ab7e3
Revises: 40f8af84ecb8
Create Date: 2024-06-25 14:37:29.255400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b022a93ab7e3'
down_revision: Union[str, None] = '40f8af84ecb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baskets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='basketstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baskets_id'), 'baskets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_baskets_id'), table_name='baskets')
    op.drop_table('baskets')
    # ### end Alembic commands ###
